server.port=8084
spring.application.name=employee-management-service

spring.config.import=configserver:http://localhost:8888

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*